command:
  df -h:
    磁盘使用情况
  free -m:
    内存使用情况


parser_rule:
  df -h:
    - 80
    - '{0} | {1} | 异常 | 磁盘空间利用率过高'


out_md_dir: './md_dir'
out_html_dir: 'html_dir'
pcinfo: 'pcinfo.txt'
templates: './templates'